[package]
name = "rust-websockets"
version = "0.1.0"
edition = "2021"
description = "A simple Rust WebSockets server for live-reloading SCSS files."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
notify = "6.1.1"
owo-colors = "4.0.0"
tokio = { version = "1.37", features = ["full"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
clap = { version = "4.5", features = ["derive", "cargo"] }
